services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    volumes:
      - ./api:/app
    networks:
      - cca_network
  frontend:
    build:
      context: care-ml
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8501:8501
    volumes:
      - ./care-ml:/app
    networks:
      - cca_network
    depends_on:
      - api
      - ml
    command: streamlit run app.py
  ml:
    build:
      context: care-ml
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3050:3050
    volumes:
      - ./care-ml:/app
    networks:
      - cca_network
    depends_on:
      - api

networks:
  cca_network:
    driver: bridge
